site_name: CAICHAT.AI

theme:
  language: en
  name: material
  features:
    - navigation.expand
    - navigation.top
    - navigation.footer

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - assets/style/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - glightbox:
      manual: true

nav:
  - Profile:
    - Profile Settings: profile-settings.md
    - User Personas: user-personas.md
  - Characters:
    - Characters Catalog: characters-catalog.md
    - Character Chats: character-chats.md
    - Creating Chatbot: creating-chatbot.md
  - Advanced:
    - Tokens: tokens.md
    - Generation Settings: generation-settings.md
    - Image Prompts: image-prompts.md